version: '3.7'

networks:
  leaderboard-net:
    driver: bridge

services:
  redis:
    image: redis:latest
    container_name: redis-server
    networks:
      - leaderboard-net
    ports:
      - "6379:6379"

  webapi:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: leaderboard-webapi
    ports:
      - "5000:5000"
    environment:
      - ASPNETCORE_URLS=http://+:5000
      - ASPNETCORE_HTTP_PORT=https://+:5001
    networks:
      - leaderboard-net
    depends_on:
      - redis
